rails g jsonapi:resource contributor username:string avatar_url:string html_url:string contributions:integer created_at:datetime updated_at:datetime
rails g jsonapi:resource friendly_id_slug slug:string sluggable_id:integer sluggable_type:string scope:string created_at:datetime
rails g jsonapi:resource hardware_item name:string alternate_name:string description:string hardware_type_id:integer compatible_with_all_vehicles:boolean available_for_purchase:boolean purchase_url:string requires_assembly:boolean can_be_built:boolean build_plans_url:string notes:string image_url:string install_guide_url:string created_at:datetime updated_at:datetime
rails g jsonapi:resource hardware_type name:string description:string created_at:datetime updated_at:datetime
rails g jsonapi:resource login identification:string password_digest:string oauth2_token:string uid:string single_use_oauth2_token:string user_id:integer created_at:datetime updated_at:datetime provider:string
rails g jsonapi:resource modification name:string summary:string description:string instructions:string created_at:datetime updated_at:datetime
rails g jsonapi:resource pull_request name:string number:string title:string state:string locked:string user:string body:string pr_created_at:string pr_updated_at:string closed_at:string merged_at:string merge_commit_sha:string head:string author_association:string html_url:string created_at:datetime updated_at:datetime
rails g jsonapi:resource repository name:string full_name:string owner_login:string owner_avatar_url:string owner_url:string url:string created_at:datetime updated_at:datetime
rails g jsonapi:resource user username:string email:string slack_username:string github_username:string created_at:datetime updated_at:datetime avatar_url:string
rails g jsonapi:resource vehicle_capability name:string description:string created_at:datetime updated_at:datetime
rails g jsonapi:resource vehicle_config_capability vehicle_config_id:integer vehicle_capability_id:integer kph:integer timeout:integer confirmed:boolean confirmed_by:integer notes:string created_at:datetime updated_at:datetime vehicle_config_type_id:integer
rails g jsonapi:resource vehicle_config_hardware vehicle_config_id:integer hardware_item_id:integer created_at:datetime updated_at:datetime
rails g jsonapi:resource vehicle_config_pull_request vehicle_config_id:integer pull_request_id:integer created_at:datetime updated_at:datetime
rails g jsonapi:resource vehicle_config_repository vehicle_config_id:integer repository_id:integer created_at:datetime updated_at:datetime
rails g jsonapi:resource vehicle_config_required_option vehicle_config_id:integer vehicle_option_id:integer created_at:datetime updated_at:datetime
rails g jsonapi:resource vehicle_config_required_package vehicle_config_id:integer vehicle_make_package_id:integer created_at:datetime updated_at:datetime
rails g jsonapi:resource vehicle_config_statuse name:string description:string created_at:datetime updated_at:datetime
rails g jsonapi:resource vehicle_config_type name:string description:string difficulty_level:integer created_at:datetime updated_at:datetime
rails g jsonapi:resource vehicle_config_video vehicle_config_id:integer video_id:integer created_at:datetime updated_at:datetime
rails g jsonapi:resource vehicle_config title:string year:integer vehicle_make_id:integer vehicle_model_id:integer vehicle_trim_id:integer vehicle_config_status_id:integer description:string created_at:datetime updated_at:datetime vehicle_make_package_id:integer slug:string parent_id:integer vehicle_config_type_id:integer
rails g jsonapi:resource vehicle_make_package name:string vehicle_make_id:integer created_at:datetime updated_at:datetime
rails g jsonapi:resource vehicle_make name:string created_at:datetime updated_at:datetime slack_channel:string slug:string
rails g jsonapi:resource vehicle_model_option vehicle_year:integer vehicle_make_id:integer vehicle_model_id:integer vehicle_option_id:integer vehicle_option_availability_id:integer created_at:datetime updated_at:datetime
rails g jsonapi:resource vehicle_model name:string vehicle_make_id:integer tmp_make_name:string created_at:datetime updated_at:datetime slug:string
rails g jsonapi:resource vehicle_option_availability name:string created_at:datetime updated_at:datetime
rails g jsonapi:resource vehicle_option name:string description:string created_at:datetime updated_at:datetime alternate_name:string what_it_does:string what_it_doesnt_do:string reference_url:string
rails g jsonapi:resource vehicle_trim vehicle_make_id:integer vehicle_model_id:integer make_id:string make_display:string name:string trim:string year:string body:string engine_position:string engine_cc:integer engine_cyl:integer engine_type:string engine_valves_per_cyl:integer engine_power_ps:string engine_power_rpm:integer engine_torque_nm:string engine_torque_rpm:integer engine_bore_mm:integer engine_stroke_mm:integer engine_compression:string engine_fuel:string top_speed_kph:integer zero_to_100_kph:integer drive:string drive2:string seats:integer seats2:integer weight_kg:integer length_mm:integer width_mm:integer height_mm:integer wheelbase_mm:integer lkm_hwy:integer lkm_mixed:integer lkm_city:integer fuel_cap_l:integer sold_in_us:boolean co2:string created_at:datetime updated_at:datetime forward_collision_warning:integer adaptive_cruise_control:integer lane_departure_warning:integer lane_keeping_assist:integer blind_spot_warning:integer rear_cross_traffic_alert:integer back_up_camera:integer adaptive_headlights:integer antilock_braking_system:integer automatic_emergency_braking:integer automatic_parallel_parking:integer backup_warning:integer biycle_detection:integer blind_spot_monitoring:integer brake_assist:integer curve_speed_warning:integer drowsiness_alert:integer electronic_stability_control:integer high_speed_alert:integer hill_descent_assist:integer hill_start_assist:integer left_turn_crash_avoidance:integer pedestrian_detection:integer push_button_start:integer sideview_camera:integer temperature_warning:integer tire_pressure_monitoring_system:integer traction_control:integer obstacle_detection:integer
rails g jsonapi:resource version_association version_id:integer foreign_key_name:string foreign_key_id:integer
rails g jsonapi:resource version item_type:string item_id:integer event:string whodunnit:string object:string created_at:datetime object_changes:string transaction_id:integer
rails g jsonapi:resource video_hardware video_id:integer hardware_item_id:integer created_at:datetime updated_at:datetime
rails g jsonapi:resource video title:string video_url:string provider_name:string author:string author_url:string thumbnail_url:string description:string html:string uploaded_at:string created_at:datetime updated_at:datetime
rails g jsonapi:resource vote votable_type:string votable_id:integer voter_type:string voter_id:integer vote_flag:boolean vote_scope:string vote_weight:integer created_at:datetime updated_at:date