class ChangeFieldsInTrims < ActiveRecord::Migration[5.2]
  def change
    change_column :vehicle_trims, :forward_collision_warning,'integer USING CAST(forward_collision_warning AS integer)'
    change_column :vehicle_trims, :adaptive_cruise_control,'integer USING CAST(adaptive_cruise_control AS integer)'
    change_column :vehicle_trims, :lane_departure_warning,'integer USING CAST(lane_departure_warning AS integer)'
    change_column :vehicle_trims, :lane_keeping_assist,'integer USING CAST(lane_keeping_assist AS integer)'
    change_column :vehicle_trims, :blind_spot_warning,'integer USING CAST(blind_spot_warning AS integer)'
    change_column :vehicle_trims, :rear_cross_traffic_alert,'integer USING CAST(rear_cross_traffic_alert AS integer)'
    change_column :vehicle_trims, :back_up_camera,'integer USING CAST(back_up_camera AS integer)'
    change_column :vehicle_trims, :adaptive_headlights,'integer USING CAST(adaptive_headlights AS integer)'
    change_column :vehicle_trims, :antilock_braking_system,'integer USING CAST(antilock_braking_system AS integer)'
    change_column :vehicle_trims, :automatic_emergency_braking,'integer USING CAST(automatic_emergency_braking AS integer)'
    change_column :vehicle_trims, :automatic_parallel_parking,'integer USING CAST(automatic_parallel_parking AS integer)'
    change_column :vehicle_trims, :backup_warning,'integer USING CAST(backup_warning AS integer)'
    change_column :vehicle_trims, :biycle_detection,'integer USING CAST(biycle_detection AS integer)'
    change_column :vehicle_trims, :blind_spot_monitoring,'integer USING CAST(blind_spot_monitoring AS integer)'
    change_column :vehicle_trims, :brake_assist,'integer USING CAST(brake_assist AS integer)'
    change_column :vehicle_trims, :curve_speed_warning,'integer USING CAST(curve_speed_warning AS integer)'
    change_column :vehicle_trims, :drowsiness_alert,'integer USING CAST(drowsiness_alert AS integer)'
    change_column :vehicle_trims, :electronic_stability_control,'integer USING CAST(electronic_stability_control AS integer)'
    change_column :vehicle_trims, :high_speed_alert,'integer USING CAST(high_speed_alert AS integer)'
    change_column :vehicle_trims, :hill_descent_assist,'integer USING CAST(hill_descent_assist AS integer)'
    change_column :vehicle_trims, :hill_start_assist,'integer USING CAST(hill_start_assist AS integer)'
    change_column :vehicle_trims, :left_turn_crash_avoidance,'integer USING CAST(left_turn_crash_avoidance AS integer)'
    change_column :vehicle_trims, :pedestrian_detection,'integer USING CAST(pedestrian_detection AS integer)'
    change_column :vehicle_trims, :push_button_start,'integer USING CAST(push_button_start AS integer)'
    change_column :vehicle_trims, :sideview_camera,'integer USING CAST(sideview_camera AS integer)'
    change_column :vehicle_trims, :temperature_warning,'integer USING CAST(temperature_warning AS integer)'
    change_column :vehicle_trims, :tire_pressure_monitoring_system,'integer USING CAST(tire_pressure_monitoring_system AS integer)'
    change_column :vehicle_trims, :traction_control,'integer USING CAST(traction_control AS integer)'
  end
end
